"""Recognising generated files, and refusing to make them disappear.

Anthropic's action strips these before the model sees the diff, and the idea is
right: ten thousand lines of regenerated protobuf push the hand-written code out
of the reviewer's attention and cost input tokens for the privilege.

Stripping them silently is the part that is wrong, and most of the tests below
are about that half. Generated CI configuration decides what runs and as whom.
A compromised generator puts a real vulnerability in real output. Files get
hand-edited under a stale banner. And an attacker can type `@generated` into a
file they wrote themselves — a rule that hides code on request is a rule worth
attacking.
"""

from __future__ import annotations

import pytest

from security_agent.generated import HEADER_LINES, classify, partition, source_of

# ------------------------------------------------------------- recognition


@pytest.mark.parametrize("head,expected", [
    ("// Code generated by protoc-gen-go. DO NOT EDIT.\n", "Go generator banner"),
    ("/* @generated by the thing */\n", "@generated marker"),
    ("# Generated by the protocol buffer compiler.  DO NOT EDIT!\n", "protoc"),
    ("/**\n * Generated by OpenAPI Generator\n */\n", "OpenAPI Generator"),
    ("// <auto-generated>\n", "C# auto-generated banner"),
    ("# AUTO-GENERATED FILE. DO NOT MODIFY\n", "auto-generated banner"),
])
def test_a_banner_is_recognised_and_named(head, expected):
    """The reason is reported, not just the verdict. "Generated" without a
    reason is a claim the reader cannot check."""
    assert classify("some/file.go", head) == expected


@pytest.mark.parametrize("path", [
    "api/service.pb.go", "api/service_pb2.py", "web/node_modules/x/index.js",
    "vendor/github.com/x/y.go", "lib/model.g.dart", "src/routes.generated.ts",
])
def test_a_path_alone_can_be_enough(path):
    """Where a file sits is a fact about the repository. An attacker who moves
    a file into `node_modules/` has made that the finding."""
    assert classify(path) is not None


def test_ordinary_code_is_not_generated():
    assert classify("app/views.py", "def get_user(request):\n    pass\n") is None
    assert classify("app/views.py") is None


def test_a_marker_below_the_header_does_not_count():
    """Scanning the whole body would let a banner inside a string literal or a
    test fixture reclassify hand-written code."""
    body = "\n".join(["import os"] * (HEADER_LINES + 2) + ["# @generated"])
    assert classify("app/views.py", body) is None


def test_the_first_matching_reason_is_the_specific_one():
    head = "// Code generated by protoc-gen-go. DO NOT EDIT.\n// @generated\n"
    assert classify("x.go", head) == "Go generator banner"


# --------------------------------------------------- de-prioritise, not hide


def test_partition_keeps_every_path_on_one_side_or_the_other():
    """Nothing is dropped. The generated ones carry a reason; that is the whole
    difference between de-prioritising and hiding."""
    reviewed, generated_files = partition({
        "app/views.py": "def f():\n    pass\n",
        "api/service.pb.go": "",
        "ci/deploy.yml": "# @generated by the pipeline templater\n",
    })

    assert reviewed == ["app/views.py"]
    assert set(generated_files) == {"api/service.pb.go", "ci/deploy.yml"}
    assert all(reason for reason in generated_files.values())


def test_generated_ci_configuration_is_still_labelled_not_excluded():
    """It decides what runs and as whom. A tool that made it invisible would be
    blind to the most consequential generated file in most repositories."""
    _, generated_files = partition({"ci/deploy.yml": "# @generated\n"})
    assert "ci/deploy.yml" in generated_files


def test_the_classifier_points_at_the_input_rather_than_the_output():
    """The security question about generated output is almost never about the
    output — it is whether the schema or the generator moved underneath it."""
    assert source_of("api/service.pb.go").endswith(".proto")
    assert source_of("clients/openapi_client.py") != ""
    assert "generator" in source_of("whatever.ts")


def test_a_hand_written_file_carrying_a_stale_banner_is_still_readable():
    """The classification is advisory. Nothing here removes a file from the
    tools, so a marker cannot make code unreadable — only lower its priority.
    """
    reviewed, generated_files = partition({"app/handler.go": "// @generated\nreal code\n"})

    assert reviewed == []
    assert "app/handler.go" in generated_files
    # And the reason is stated, so a reader who disagrees can go and look.
    assert generated_files["app/handler.go"] == "@generated marker"
