"""Recognising generated files, and de-prioritising rather than hiding them.

A diff carrying ten thousand lines of regenerated protobuf pushes the code a
person actually wrote out of the reviewer's attention, and every line of it
costs input tokens. Anthropic's own action strips these before the model sees
the diff, and the idea is right.

Stripping them silently is not. Generated output is security-relevant more
often than its label suggests:

* generated CI and deployment configuration decides what runs and as whom;
* generated API clients carry credential and URL handling;
* a compromised generator introduces a real vulnerability into real output;
* files get hand-edited under a stale generator banner;
* an attacker can add a recognised marker to a file they wrote by hand.

So this classifies and explains. The body leaves the initial diff; the path,
the size, and the reason stay in the briefing, and the agent can still open the
file. What the reader gets is "these were set aside, here is why", never
silence.

The last of those reasons is why a marker is never trusted on its own to make a
file invisible: a rule an attacker can satisfy by typing a comment is a rule
that hides code on request.
"""

from __future__ import annotations

import re
from typing import Dict, List, Optional, Tuple

# Only the first lines are searched. A generator banner sits at the top of the
# file by convention, and scanning the whole body would let a marker buried in
# a string literal or a test fixture reclassify hand-written code.
HEADER_LINES = 8

# Ordered: the first match wins, so the more specific reason is reported.
_MARKERS: Tuple[Tuple[str, str], ...] = (
    # The Go convention, and the closest thing to a cross-language standard.
    (r"^//\s*Code generated .* DO NOT EDIT\.?$", "Go generator banner"),
    (r"@generated\b", "@generated marker"),
    (r"^#\s*Generated by the protocol buffer compiler", "protoc"),
    (r"Generated by OpenAPI Generator", "OpenAPI Generator"),
    (r"Generated by protoc-gen-\w+", "protoc-gen"),
    (r"^#\s*Code generated by\b", "generator banner"),
    (r"AUTO-GENERATED FILE\. DO NOT MODIFY", "auto-generated banner"),
    (r"^//\s*<auto-generated", "C# auto-generated banner"),
    (r"This file was automatically generated", "automatic generation notice"),
    (r"DO NOT EDIT THIS FILE", "do-not-edit banner"),
)

_COMPILED = tuple((re.compile(pattern, re.IGNORECASE | re.MULTILINE), reason)
                  for pattern, reason in _MARKERS)

# Paths whose generated-ness is a property of where they are, not what they
# say. Kept separate from the markers because an attacker cannot move a file
# into `node_modules/` without that itself being the finding.
_PATH_MARKERS: Tuple[Tuple[str, str], ...] = (
    (r"(^|/)node_modules/", "vendored dependency"),
    (r"(^|/)vendor/", "vendored dependency"),
    (r"\.pb\.go$", "protobuf output"),
    (r"_pb2\.pyi?$", "protobuf output"),
    (r"\.g\.dart$", "generated Dart"),
    (r"\.generated\.[a-z]+$", "generated by name"),
)

_COMPILED_PATHS = tuple((re.compile(pattern), reason)
                        for pattern, reason in _PATH_MARKERS)


def classify(path: str, head: str = "") -> Optional[str]:
    """Why this file counts as generated, or None.

    `head` is the first few lines of the file. Passing an empty string checks
    the path alone, which is what a caller with only a file list can do.
    """
    for pattern, reason in _COMPILED_PATHS:
        if pattern.search(path or ""):
            return reason
    if not head:
        return None
    window = "\n".join(head.splitlines()[:HEADER_LINES])
    for pattern, reason in _COMPILED:
        if pattern.search(window):
            return reason
    return None


def partition(files: Dict[str, str]) -> Tuple[List[str], Dict[str, str]]:
    """Split `{path: head}` into (reviewed, {generated path: reason})."""
    reviewed, generated = [], {}
    for path in sorted(files):
        reason = classify(path, files[path])
        if reason:
            generated[path] = reason
        else:
            reviewed.append(path)
    return reviewed, generated


def source_of(path: str) -> str:
    """The input a generated file most likely came from, as a search hint.

    Not a lookup — a suggestion for where to look. The security question about
    generated output is almost never about the output: it is whether the schema
    it was generated from, or the generator itself, changed underneath it.
    """
    if path.endswith(".pb.go") or path.endswith("_pb2.py"):
        return path.rsplit(".", 1)[0].replace("_pb2", "") + ".proto"
    if "openapi" in path.lower() or "swagger" in path.lower():
        return "the OpenAPI specification this client was generated from"
    return "the schema, template or generator configuration this came from"
